name: "Lint & Test"

on:
  ["push", "pull_request"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install packages
        run: yarn
      - name: Lint files
        run: yarn lint